### ISSUE TITLE
références des témoignages

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#10]
Faire apparaître pour chaque fragment ou témoignages toutes les références de ce fragment dans les différentes éditions (signalées par un <bibl>)

**Comment by jmague** [comment]
on type les *bibl*, par exemple avec *principal* et *secondaire*

**Comment by mingarao** [comment]
question reprise dans #41 
la ref princiaple est celle de l'édition de @smarchand  (@xml:id ou @n à déterminer)
