### ISSUE TITLE
mots-clefs comme facette dans la navigation verticale

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#20]
1. restreindre les mots clefs à ceux des fragments, ou des auteurs affichés

**Comment by vbeaugiraud** [comment]
- Facette "Nom d'Auteur" pour la partie "Notiones" 
- Facette "Notiones" pour les parties "Volumina" et Sceptici"

**Comment by mingarao** [comment]
En cours, à contrôler
Faire la même chose pour les sceptiques ?
Pour les auteurs ?
Pour les titres d'oeuvre ?
Ou pas d'intérêt ?

**Comment by smarchand** [comment]
a priori cela aurai un intérêt à développer, mais il vaut mieux qu'on en parle de vive voix pour que je me réprésente ce que cela donnerait
