### ISSUE TITLE
afficher les <title> en  italiques

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#23]

**Comment by mingarao** [comment]
ok, traité quand on appelle la xsl skepsis.xsl
Mais cet appel plante dans certains cas (page d'un sceptique ou page d'une notion)

**Comment by smarchand** [comment]
ok merci !
je ne comprends pas ce commentaire , tu ne t'es pas trompée de ticket ?

Le 9 juin 2015 18:00, mingarao <notifications@github.com> a écrit :

> ok, traité quand on appelle la xsl skepsis.xsl
> Mais cet appel plante dans certains cas (page d'un sceptique ou page d'une
> notion)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/23#issuecomment-110415078>.
>



-- 
Stéphane

**Comment by mingarao** [comment]
Non c'est bien le bon fil :)
Les balises title sont traitées grace à la xsl skepsis.xsl (cela règle le fait qu'elles n'apparaissaient pas ET la demande de les faire apparaître en italique)
Par contre cette xsl fait planter certaines pages, je regarde justement cela cet aprem.

**Comment by mingarao** [comment]
A contrôler

**Comment by smarchand** [comment]
les italiques marchaient mais cela ne marche plus
