### ISSUE TITLE
corriger le site http://ahn.ens-lyon.fr/node/36

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#25]
il faut ajouter un lien vers skepsis;
et corriger l'UMR en UMR 5037 (IHPC)

**Comment by mingarao** [comment]
Demandé à la webmestre du site de porter la correction

**Comment by mingarao** [comment]
Elle a corrigé l'UMR
Pour le lien on attend d'avoir versé la version actuelle sur editions.ihpc.huma-num.fr ?

**Comment by smarchand** [comment]
OK

2015-06-11 20:01 GMT+02:00 mingarao <notifications@github.com>:

> Elle a corrigé l'UMR
> Pour le lien on attend d'avoir versé la version actuelle sur
> editions.ihpc.huma-num.fr ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/25#issuecomment-111224470>.
>



-- 
Stéphane
