### ISSUE TITLE
[encodage] mettre des id au TEI

### ISSUE THREAD

**Issue by jmague** [umr5037/skepsis#26]
Chaque texte devrait avoir un id. Ces id doivents etre basés sur les titres. Ce sont eux que l'on verrait dans les URL

**Comment by smarchand** [comment]
par "texte" vous voulez dire chaque "volumen" ?

2015-06-11 17:37 GMT+02:00 mingarao <notifications@github.com>:

> Assigned #26 <https://github.com/umr5037/skepsis/issues/26> to @smarchand
> <https://github.com/smarchand>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/26#event-328629268>.
>



-- 
Stéphane

**Comment by mingarao** [comment]
Oui, un attribut xml:id dans la balise racine de chaque TEI

L'idéal serait de créer des xml:id lisibles à l'oeil humain, mais "urlisés" soit : tout en minuscules, espaces remplacés par des tirets, pas de caractères "exotiques" (supprimés)

par exemple, 
* pour De Finibus : de-finibus
* pour Adversus Mathematicos VII-XI : adversus-mathematicos-vii-xi

etc.

Afin que nous puissions remplacer les titres des oeuvres par ces xml:id dans les url
Cela évitera les horribles url avec des %20 à la place des espaces quand on voudra communiquer les url des textes dans des mails par exemple :)

url sur le modèle du Monde par exemple sans tenir compte des chiffres à la fin http://www.lemonde.fr/football/article/2015/06/11/mondial-quand-les-footballeuses-doivent-montrer-qu-elles-sont-des-femmes_4652389_1616938.html

Ainsi
http://localhost:8984/skepsis/volumina/Adversus%20Mathematicos%20VII-XI/livre/VIII/chapitre/8 deviendra
http://localhost:8984/skepsis/volumina/adversus-mathematicos-vii-xi/livre/VIII/chapitre/8

**Comment by smarchand** [comment]
OK, je ne dois pas être en forme, je ne trouve pas d'endroit pour mettre
ces id ; on verra ensemble et je le ferai


Le 11 juin 2015 19:04, mingarao <notifications@github.com> a écrit :

> Oui, un attribut xml:id dans la balise racine de chaque TEI
>
> L'idéal serait de créer des xml:id lisibles à l'oeil humain, mais
> "urlisés" soit : tout en minuscules, espaces remplacés par des tirets, pas
> de caractères "exotiques" (supprimés)
>
> par exemple,
>
>    - pour De Finibus : de-finibus
>    - pour Adversus Mathematicos VII-XI : adversus-mathematicos-vii-xi
>
> etc.
>
> Afin que nous puissions remplacer les titres des oeuvres par ces xml:id
> dans les url
> Cela évitera les horribles url avec des %20 à la place des espaces quand
> on voudra communiquer les url des textes dans des mails par exemple :)
>
> url sur le modèle du Monde par exemple sans tenir compte des chiffres à la
> fin
> http://www.lemonde.fr/football/article/2015/06/11/mondial-quand-les-footballeuses-doivent-montrer-qu-elles-sont-des-femmes_4652389_1616938.html
>
> Ainsi
>
> http://localhost:8984/skepsis/volumina/Adversus%20Mathematicos%20VII-XI/livre/VIII/chapitre/8
> deviendra
>
> http://localhost:8984/skepsis/volumina/adversus-mathematicos-vii-xi/livre/VIII/chapitre/8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/26#issuecomment-111207827>.
>



-- 
Stéphane

**Comment by mingarao** [comment]
Par exemple pour Sextus AM

TEI xml:id="adversus-mathematicos-vii-xi"
                 teiHeader
                  .....
                  text
                        body 
                            div type = livre
                                 etc.

Mais on verra ça...

**Comment by smarchand** [comment]
OK ! je l'ai fait. vous me direz si cela marche

2015-06-12 15:52 GMT+02:00 mingarao <notifications@github.com>:

> Par exemple pour Sextus AM
>
> TEI xml:id="adversus-mathematicos-vii-xi"
> teiHeader
> .....
> text
> body
> div type = livre
> etc.
>
> Mais on verra ça...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/26#issuecomment-111500032>.
>



-- 
Stéphane
