### ISSUE TITLE
De Finibus

### ISSUE THREAD

**Issue by mingarao** [umr5037/skepsis#31]
Commence directement par une balise q et non une balise ab. Est-ce normal ?
En attendant de savoir j'adapte la requête xquery à ce cas

**Comment by smarchand** [comment]
oui c'est normal, c'est pareil pour le début d'Eusebius, c'est le cas où on
a des fragments qui citent directement quelqu'un (des fragmentums) ; donc
on peut dire que ce sont des citations.
Dis-donc cela marche drôlement bien ce que tu as fait ! je travaille
dessus, c'est top !

Le 10 juin 2015 14:58, mingarao <notifications@github.com> a écrit :

> Commence directement par une balise q et non une balise ab. Est-ce normal ?
> En attendant de savoir j'adapte la requête xquery à ce cas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/31>.
>



-- 
Stéphane

**Comment by mingarao** [comment]
ok merci :) la requête est adaptée
(mais je me demande si on ne devrait pas quand même ajouter un ab englobant, à voir...)
