### ISSUE TITLE
Ne s'affichent pas

### ISSUE THREAD

**Issue by mingarao** [umr5037/skepsis#32]
- le texte Sextus PH (seulement le titre)
- la requête sur le sceptique Sextus 

pas vu pourquoi à ce stade

**Comment by smarchand** [comment]
c'est sûrement parce que Sextus est un cas particulier :
c'est à la fois un auteur de volumen et un scepticus
du coup tel que l'encodage est fait les requêtes sur Sextus ne doivent pas
ramèner à des corresp ou des source, mais à ses livres dans les volumina.

Le 10 juin 2015 17:37, mingarao <notifications@github.com> a écrit :

>
>    - le texte Sextus PH (seulement le titre)
>    - la requête sur le sceptique Sextus
>
> pas vu pourquoi à ce stade
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/32>.
>



-- 
Stéphane

**Comment by mingarao** [comment]
Est-ce que Sextus peut en tant qu'auteur citer d'autres sceptiques et/ou se citer lui-même ?

Dans tous les cas il me semble qu'il faudrait garder le même encodage (dans la balise author pour les textes dont il est l'auteur, dans les corresp s'il se cite lui même ou s'il est cité par d'autres auteurs)

Du coup ça devient je pense une question d'encodage à trancher avant d'être un bug...

**Comment by smarchand** [comment]
il peut citer d'autres sceptiques, mais a priori il ne se cite pas lui-même.
Le problème c'est à quel niveau je dois mettre cette balise ?
et pour l'instant on a jamais utiliser cette balise (on a utilisé) <auth>

Le 11 juin 2015 17:45, mingarao <notifications@github.com> a écrit :

> Est-ce que Sextus peut en tant qu'auteur citer d'autres sceptiques et/ou
> se citer lui-même ?
>
> Dans tous les cas il me semble qu'il faudrait garder le même encodage
> (dans la balise author pour les textes dont il est l'auteur, dans les
> corresp s'il se cite lui même ou s'il est cité par d'autres auteurs)
>
> Du coup ça devient je pense une question d'encodage à trancher avant
> d'être un bug...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/32#issuecomment-111178247>.
>



-- 
Stéphane

**Comment by mingarao** [comment]
la balise author y est déjà (c'est dans le teiHeader, dans titleStmt) donc en tant qu'auteur c'est bon.

Par contre si on veut que ses propres textes apparaissent quand on l'intérroge en tant que sceptique, je propose de le mettre dans l'attribut corresp des passages correspondants, exactement comme les autres sceptiques, plutôt que de créer un mécanisme spécifique qui va complexifier le code.

Sauf si ça fausse la lecture et la compréhension bien sûr.

**Comment by mingarao** [comment]
En fait c'était un pb d'encodage 

Sextus AM marchait, seul Sextus PH ne marchait pas, c'est parce que le livre 3 était englobé dans le  livre précédent au lieu d'être après.

corrigé.

Sinon Sextus en tant que Sceptique ne renvoie rien mais là c'est normal, c'est qu'il n'est jamais mentionné en attribut corresp.

**Comment by smarchand** [comment]
OK, mais du coup pour l'encodage, je ne vois pas très bien où mettre ce
corresp pour qu'il englobe tout le volumen ! C'est un cas particulier, mais
il est important (c'est notre source majeure).
Dans l'idéal, il faudrait que la requête "Sextus" comme sceptici donne
accès la liste de ces volumen, puis au contenu de ces textes.

2015-06-11 19:38 GMT+02:00 mingarao <notifications@github.com>:

> Closed #32 <https://github.com/umr5037/skepsis/issues/32>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/32#event-328747421>.
>



-- 
Stéphane
