### ISSUE TITLE
textes en double

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#33]
Certains textes apparaissent deux fois, avec parfois seulement la traduction française dans la colonne du grec.Il doit  y avoir un pb dans la requête. Ex : http://ahn-basex.cbp.ens-lyon.fr:8984/skepsis/sceptici/Pyrrho

**Comment by mingarao** [comment]
ok réglé

comptabilisait les parties de texte type="translatio" et corresp="#Arcesilas_F9" par exemple comme un fragment tagué avec le sceptique Arcesilas

Exclu les parties de texte de type translatio ou fils de translatio dans getTextPartByScepticus et getTextPartByNotio
