### ISSUE TITLE
milestones ou ref entre crochets ?

### ISSUE THREAD

**Issue by mingarao** [umr5037/skepsis#36]
Dans certains textes on a certains paragraphes encodés sous forme de milestones (exemple Photius paragraphe 169b) et d'autres notés juste entre crochets (exemple Photius [170a18])

Différence ?

Actuellement les paragraphes entre crochets ne peuvent pas être traités comme des paragraphes (uniquement les milestones sont traités)

**Comment by smarchand** [comment]
oui c'est normal, c'est juste que dans la traduction je renvoie à des
lignes du texte original. Il faudrait que je trouve un moyen pour l'encoder
proprement dans le grec mais je n'ai pas encore trouvé (ni vraiment cherché
du reste)

2015-06-11 17:40 GMT+02:00 mingarao <notifications@github.com>:

> Assigned #36 <https://github.com/umr5037/skepsis/issues/36> to @smarchand
> <https://github.com/smarchand>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/36#event-328632287>.
>



-- 
Stéphane

**Comment by smarchand** [comment]
ok je vais tout faire avec des milestones
