### ISSUE TITLE
pb avec les persName

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#40]
j'utilise des ref dans les persName, par exemple <persName ref="Aenesidemus">
du coup cela renvoie le texte entre la balise comme du texte attribué à ce philosophe.
VOir par exemple ici : http://ahn-basex.cbp.ens-lyon.fr:8984/skepsis/sceptici/Aenesidemus

**Comment by mingarao** [comment]
je savais que c'était dangereux @* :) @jmague
