### ISSUE TITLE
id des textes (fragments et témoignages) et <bibl>

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#41]
Je récapitule ma demande pour la présentation des fragments et témoignages : 
+ chaque texte (fragmentum ou testimonium) a un xml id (avec un ref, pour que ce soit affichable) qui va servir de référence principale
+ par ailleurs, il y a une information dans <bibl> qui donne les équivalences dans d'autres éditions.

Donc quand on a un fragment, l'idéal serait que son nom (son id, ou le ref associé) apparaisse. Et qu'ailleurs, si on clique quelque part, on ait les données des <bibl>.
Cela donnerait cela
Nom principal (pour Pyrrhon par ex) : T1 Pyrrhon, puis si on clique sur le bouton <bibl> : = T 53 Decleva Caizzi ; T 37 LS, etc...
c'est un point important pour ma démo

**Comment by mingarao** [comment]
Actuellement, les références  des ```<bibl/>``` sont données au survol sur les T et les F

A reprendre si besoin d'un comportement différent
