### ISSUE TITLE
div type page pour les livres sans chapitre

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#44]
trouver un système pour les textes qui n'ont pas de chapitre (par exemple Diogenes Laertius, Sextus, etc..) : dans ces textes la structure sera : div type livre, div type page, puis les milestones.

**Comment by mingarao** [comment]
A priori, c'est fait :)
Encoder des textes avec des sous-sections de type "page" pour contrôler

**Comment by smarchand** [comment]
ça marche pour page, mais du coup quand il y a des chapitres cela ne
s'affiche plus ...

2015-07-08 15:32 GMT+02:00 mingarao <notifications@github.com>:

> A priori, c'est fait :)
> Encoder des textes avec des sous-sections de type "page" pour contrôler
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/44#issuecomment-119579872>.
>



-- 
Stéphane

**Comment by mingarao** [comment]
Peux-tu donner une url où ça ne marche pas ?
Car moi j'obtiens bien l'affichage des chapitres cf. par ex. http://ahn-basex.cbp.ens-lyon.fr:8984/skepsis/volumina/Adversus_Mathematicos_VII-XI/livre/VII/chapitre/158

**Comment by smarchand** [comment]
ah zut je ne ne suis plus à l'ens et ça ne marche pas à l'extérieur...
de mémoire, il faut essayer un cicéron (où la structure est livre,
chapitre, §)

Le 8 juillet 2015 18:51, mingarao <notifications@github.com> a écrit :

> Peux-tu donner une url où ça ne marche pas ?
> Car moi j'obtiens bien l'affichage des chapitres cf. par ex.
> http://ahn-basex.cbp.ens-lyon.fr:8984/skepsis/volumina/Adversus_Mathematicos_VII-XI/livre/VII/chapitre/158
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/44#issuecomment-119656675>.
>



-- 
Stéphane

**Comment by smarchand** [comment]
et pour les facettes quand je suis parti cela ne marchait plus, mais peut
être que tu n'avais pas fini.
Je reviens à l'ens vendredi, je ferai le point
merci pour tout !
s

Le 8 juillet 2015 18:59, Stéphane Marchand <marchand.st@gmail.com> a écrit :

> ah zut je ne ne suis plus à l'ens et ça ne marche pas à l'extérieur...
> de mémoire, il faut essayer un cicéron (où la structure est livre,
> chapitre, §)
>
> Le 8 juillet 2015 18:51, mingarao <notifications@github.com> a écrit :
>
>> Peux-tu donner une url où ça ne marche pas ?
>> Car moi j'obtiens bien l'affichage des chapitres cf. par ex.
>> http://ahn-basex.cbp.ens-lyon.fr:8984/skepsis/volumina/Adversus_Mathematicos_VII-XI/livre/VII/chapitre/158
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/umr5037/skepsis/issues/44#issuecomment-119656675>.
>>
>
>
>
> --
> Stéphane
>



-- 
Stéphane

**Comment by jmague** [comment]
Et a présent ?
Sinon, pour nous il y a un truc avec Philo Larissaeus (http://ahn-basex.cbp.ens-lyon.fr:8984/skepsis/sceptici/Philo_Larissaeus). Il n'a pas de textes, mais il semblerait que ce soit normal car il n'est jamais en corresp ni en source. Non ?

**Comment by smarchand** [comment]
oui c'est normal

Le 9 juillet 2015 15:52, Jean-Philippe Magué <notifications@github.com> a
écrit :

> Et a présent ?
> Sinon, pour nous il y a un truc avec Philo Larissaeus (
> http://ahn-basex.cbp.ens-lyon.fr:8984/skepsis/sceptici/Philo_Larissaeus).
> Il n'a pas de textes, mais il semblerait que ce soit normal car il n'est
> jamais en corresp ni en source. Non ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/44#issuecomment-119977082>.
>



-- 
Stéphane

**Comment by smarchand** [comment]
j'ai un autre cas qui pose problème :
il y a des livres qui n'ont pas de n° de livre. mais juste des paragraphes, comme par exemple Philo Alexandrinus.
Pour ce cas il faudrait soit qu'il n'y ait pas de div type livre, soit que la div type livre n'ait pas de n°

**Comment by smarchand** [comment]
bon là j'ai rusé en mettant un "_" à la place du n°, et ça marche.
je laisse ouvert l'issue, mais ce n'est plus urgent

**Comment by mingarao** [comment]
A régler :

http://ahn-basex.cbp.ens-lyon.fr:8984/skepsis/volumina/De_ebrietate/livre/%20/page/1
