### ISSUE TITLE
Tri par facette

### ISSUE THREAD

**Issue by mingarao** [umr5037/skepsis#47]
Principe : lorsqu'on sur un philosophe, apparaissent les notiones liés au texte du philosophe, et si on clique sur la notio, on a les textes du philosophe en question lié à la facette

**Comment by mingarao** [comment]
S'il y a plusieurs notions, doit-on pouvoir cumuler les choix ?

**Comment by mingarao** [comment]
Fonctionne pour les sceptici

Reste à implémenter depuis les notiones

Pour le moment on est parti sur croiser 1 scepticus et 1 notio

**Comment by smarchand** [comment]
j'ai réfléchi. dans l'idéal, oui il faudrait pouvoir cumuler les choix. Je propose la chose suivante : 
- soit cela ne demande pas trop de temps de développement, et on le fait maintenant
- sinon on prévoit cela pour la prochaine session de développement parce que c'est trop long, et dans ce cas on fait une issue de priorité 2 par exemple

**Comment by mingarao** [comment]
Vu les interventions urgentes que j'ai encore sur les corpus Rey et Bvm, je vote pour le choix 2 :+1: 
:)
