### ISSUE TITLE
balise bibl

### ISSUE THREAD

**Issue by smarchand** [umr5037/skepsis#59]
Pour l'info bulle avec les références des fragments : 
- il y a d'abord une balise `<listBibl>`
- puis une ou plusieurs `<bibl>`
Il faut que l'info bulle donne l'xml id (c'est déjà le cas) ; puis le signe "=" ; puis la liste des références dans '''<listBibl>''', chaque référence séparée par un ";"

pour l'instant ne donne qu'une seule réf. dans un `<bibl>` et n'affiche rien de ce qui est dans `<listBibl>`
Je vais adapter l'encodage pour les vacances, mais ce serait bien que ce soit affichable pour le 2 septembre

**Comment by mingarao** [comment]
Je ne comprends pas l'encodage, par exemple dans Sextus AM il y a un bibl suivi d'un listBibl avec les mêmes infos répétées. Dans d'autres textes il n'y a qu'un bibl sans listBibl

**Comment by smarchand** [comment]
j'ai bricolé cela en pensant qu'on reglerait cela à la rentrée.
Pour le future, il y a aura un <listBibl> avec des <bibl>

Le 23 juillet 2015 12:33, mingarao <notifications@github.com> a écrit :

> Je ne comprends pas l'encodage, par exemple dans Sextus AM il y a un bibl
> suivi d'un listBibl avec les mêmes infos répétées. Dans d'autres textes il
> n'y a qu'un bibl sans listBibl
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/59#issuecomment-124051461>.
>



-- 
Stéphane
