### ISSUE TITLE
Bug dans Sextus / Adversus

### ISSUE THREAD

**Issue by mingarao** [umr5037/skepsis#61]
A partir de http://ahn-basex.cbp:8984/skepsis/volumina/Adversus_Mathematicos_VII-XI/livre/7/page/5 le bouton "suivant" donne l'url http://ahn-basex.cbp:8984/skepsis/volumina/Adversus_Mathematicos_VII-XI/livre/VIIIIXXI/chapitre/818269

**Comment by smarchand** [comment]
oui, je n'y comprends rien. J'ai regardé le TEI, qui paraît bon.
le système livre/page fonctionne pourtant bien par exemple ici :
http://ahn-basex.cbp:8984/skepsis/volumina/Vitae_philosophorum/livre/4/page/1

Le 21 juillet 2015 14:43, mingarao <notifications@github.com> a écrit :

> A partir de
> http://ahn-basex.cbp:8984/skepsis/volumina/Adversus_Mathematicos_VII-XI/livre/7/page/5
> le bouton "suivant" donne l'url
> skepsis/volumina/Adversus_Mathematicos_VII-XI/livre/VIIIIXXI/chapitre/818269
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/61>.
>



-- 
Stéphane

**Comment by smarchand** [comment]
c'était une erreur d'encodage...
