### ISSUE TITLE
Notion Sorites ne s'affiche pas en titre

### ISSUE THREAD

**Issue by mingarao** [umr5037/skepsis#70]
http://editions.ihpc.huma-num.fr/skepsis/notiones/sorites

**Comment by smarchand** [comment]
il y a vait un espace dans le xml id ... j'ai corrigé, on verra si cela
change quelque chose

2015-07-23 13:40 GMT+02:00 mingarao <notifications@github.com>:

> http://editions.ihpc.huma-num.fr/skepsis/notiones/sorites
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsis/issues/70>.
>



-- 
Stéphane

**Comment by smarchand** [comment]
résolu sur ahn ; c'était l'espace dans le xml id
